### ISSUE TITLE
bug - GED_metric

### ISSUE THREAD

**Issue by Sivler9** [JulesSanchez/X-NeSyL#2]
https://github.com/JulesSanchez/X-NeSyL/blob/da333ceb84f00c821493a7c2f2828ff9dd337db4/utils/knowledge_graph.py#L167 presumably should be `features[i]`, otherwise only the first 4 are used, due to https://github.com/JulesSanchez/X-NeSyL/blob/da333ceb84f00c821493a7c2f2828ff9dd337db4/utils/knowledge_graph.py#L162 and https://github.com/JulesSanchez/X-NeSyL/blob/da333ceb84f00c821493a7c2f2828ff9dd337db4/utils/knowledge_graph.py#L166 and if the number of object classes is greater than the batch size the code would produce an Index Out of Bounds exception, if line 162 didn't limit it to 4.

https://github.com/JulesSanchez/X-NeSyL/blob/da333ceb84f00c821493a7c2f2828ff9dd337db4/utils/knowledge_graph.py#L180-L181 makes all features 0 always, which mean it does no contribution to the facade graph.

**Comment by JulesSanchez** [comment]
Hi, indeed for features[i], sorry it has been fixed but I'm delayed in pushing a up to date version. I'll do this over the vacations, it should answer most comments here.

**Comment by JulesSanchez** [comment]
Hopfully it's fixed, it had been a long time I didn't read the code.
